/**
 * @file   expression.hpp
 * @author Marvin Smith
 * @date   5/20/2026
 *
 * @brief  Header for the Expression class for handling mathematical expressions.
 */
#pragma once

// C++ Standard Libraries
#include <functional>
#include <overboard/core/keymap.hpp>
#include <overboard/math/ast/node.hpp>
#include <overboard/math/ast/node_traits.hpp>
#include <overboard/math/ast/placeholder_node.hpp>
#include <overboard/math/operators/operator.hpp>
#include <string>
#include <vector>

namespace ovb::math {

/**
 * @brief An editable expression using AST-based representation.
 * The AST root is the single source of truth for the expression.
 */
class Expression {

    public:

        /// @brief Type alias for AST node visitor functions that return strings
        using Node_Visitor_String = std::function<std::string(const ast::Node*)>;

        /**
         * @brief Constructor
         */
        Expression();

        /**
         * @brief Insert a token generated by the given key press
         * @param code The key code that generated the token
         */
        void insert( core::Key_Code code );

        /**
         * @brief Delete the node at the current cursor position
         */
        void backspace();

        /**
         * @brief Move cursor left in tree
         */
        void cursor_left();

        /**
         * @brief Move cursor right in tree
         */
        void cursor_right();

        /**
         * @brief Clear the entire tree and reset to placeholder
         */
        void clear();

        /**
         * @brief Get the evaluation string
         * @return The evaluation string
         */
        std::string eval_string() const;

        /**
         * @brief Get the render string
         * @return The render string
         */
        std::string render_string() const;

        /**
         * @brief Get the cursor glyph position
         * @return The cursor glyph position
         */
        std::size_t cursor_glyph_pos() const;

        /**
         * @brief Returns true if the expression is empty
         * @return True if the expression is empty, false otherwise
         */
        bool empty() const { return m_ast_root->kind() == ast::Node_Kind::PLACEHOLDER; }

        /**
         * @brief Returns true if any placeholder tokens exist (blocks evaluation).
         * @return True if any placeholder tokens exist, false otherwise
         */
        bool has_placeholder() const;

        /**
         * @brief Remove trailing placeholder if present (for evaluation)
         */
        void remove_trailing_placeholder();

        /**
         * @brief Get the AST root (for tree-based refactor)
         * @return The AST root
         */
        const ast::Node::ptr_t& ast_root() const { return m_ast_root; }

    private:

        /**
         * @brief Insert a digit at the current cursor position
         * @param digit The digit to insert
         */
        void insert_digit( int digit );

        /**
         * @brief Insert an operator at the current cursor position
         * @param op The operator to insert
         */
        void insert_operator( ast::Binary_Op op );

        /**
         * @brief Insert a function at the current cursor position
         * @param func The function to insert
         */
        void insert_function( const operators::I_Operator& func );

        /**
         * @brief Get the node at the current cursor position
         * @return Pointer to the node at the cursor, or nullptr if invalid
         */
        ast::Node* get_cursor_node();
        const ast::Node* get_cursor_node() const;

        /**
         * @brief Replace the node at the current cursor path with a new node
         * @param new_node The new node to insert
         */
        void replace_node_at_cursor( ast::Node::ptr_t new_node );

        /// @brief AST root for tree-based representation (initialized with placeholder)
        ast::Node::ptr_t m_ast_root;

        /// @brief Cursor path in the AST tree (for tree-based refactor)
        ast::Cursor_Path_Runtime m_cursor_path;

        /// @brief Decimal position for number editing (0 = integer mode, >0 = decimal places)
        int m_decimal_position { 0 };
};

} // namespace ovb::math
