#pragma once

#include <overboard/core/keymap.hpp>
#include <string>
#include <vector>

namespace ovb::math {

enum class Token_Type : uint8_t {
    Number,     // editable character-by-character
    Operator,   // +  -  *  /  ^  %  &  |  <<  >>
    Function,   // sin(  cos(  sqrt(  … — deleted atomically
    Constant,   // pi  e  phi  tau   — deleted atomically
    Paren,      // (  )
};

struct Token {
    Token_Type      type;
    std::string     text;       // display / eval text e.g. "3.14", "sin(", "pi"
    core::Key_Code  code;       // originating Key_Code — drives evaluation

    // Cursor offset within this token; only meaningful when type == Number.
    // Ranges 0..text.size(). -1 when cursor is not inside this token.
    int char_cursor = -1;
};

// An editable token-stream expression.
// Cursor sits between tokens (cursor_token == index of token to the LEFT of the
// cursor, or -1 when at the very start).  When the cursor is inside a Number
// token, that token's char_cursor field is set instead.
class Expression {
    public:
        Expression() = default;

        // ── Editing ──────────────────────────────────────────────────────────

        // Insert a token generated by the given key press.
        void insert( core::Key_Code code );

        // Delete the token (or character) immediately to the left of the cursor.
        void backspace();

        // Move the cursor one logical step left / right.
        void cursor_left();
        void cursor_right();

        // Clear everything.
        void clear();

        // ── Query ────────────────────────────────────────────────────────────

        // String suitable for passing to the parser / evaluator.
        std::string eval_string() const;

        // String for display (functions shown without trailing '(' if desired —
        // currently identical to eval_string, '(' included).
        std::string render_string() const;

        // Position of the cursor in *glyphs* (codepoints) within render_string().
        int cursor_glyph_pos() const;

        bool empty() const { return tokens_.empty(); }

    private:
        std::vector<Token> tokens_;

        // Index of the token the cursor is logically AFTER (-1 = before all tokens).
        int cursor_token_ = -1;

        // Helpers
        bool cursor_inside_number() const;
        Token& current_number_token();
        void close_number();          // finalize an open number token
        static Token make_token( core::Key_Code code );
        static int glyph_count( const std::string& s );
};

} // namespace ovb::math
